list = []
list.append(-133)
list.append(-133)
list.append(-133)
list.append(-133)
list.append(-133)
list.append(-133)
list.append(-133)
list.append(-133)
list.append(-133)
list.append(-133)

print(f"Slot 0 contains a {list[0]}")
print(f"Slot 1 contains a {list[1]}")
print(f"Slot 2 contains a {list[2]}")
print(f"Slot 3 contains a {list[3]}")
print(f"Slot 4 contains a {list[4]}")
print(f"Slot 5 contains a {list[5]}")
print(f"Slot 6 contains a {list[6]}")
print(f"Slot 7 contains a {list[7]}")
print(f"Slot 8 contains a {list[8]}")
print(f"Slot 9 contains a {list[9]}")
